# -*- coding: utf-8  -*-
import config, family, urllib

__version__ = '$Id: uncyclopedia_family.py 9542 2011-09-24 16:36:14Z xqt $'

#
# The Uncyclomedia family, assorted encyclopedi.as from the Uncyclopedia series.
# This file contains a full set of (currently) fifty languages, excluding forks,
# redirects and mirrors.
#
# Note that some of the wikia in this set are known to have badly incomplete,
# missing or incorrect interwiki maps. Do *not* attempt to invoke interwiki.py
# on Uncyclopedia-related wikis unless you have verified availability of
# links for all language pairs that you will plan to use as interwikis.
#

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'uncyclopedia'

        self.langs = {
            'af': 'niesiklopedia.org',
            'ar': 'beidipedia.wikia.com',
            'ast': 'nunyepedia.wikia.com',
            'bar': 'www.stupidedia.org',
            'be': 'paudurapedyja.org',
            'bg': 'bg.oxypedia.net',
            'bn': 'bn.uncyc.org',
            'bs': 'bs.neciklopedija.org',
            'ca': 'valenciclopedia.wikia.com',
            'common': 'commons.uncyclomedia.org',
            'cs': 'necyklopedie.wikia.com',
            'cy': 'cy.uncyclopedia.org.uk',
            'da': 'spademanns.wikia.com',
            'de': 'de.uncyclopedia.org',
            'dlm': 'dlm.neciklopedija.org',
            'el': 'frikipaideia.wikia.com',
            'en': 'uncyclopedia.wikia.com',
            'eo': 'neciklopedio.wikia.com',
            'es': 'inciclopedia.wikia.com',
            'et': 'ebatsuklopeedia.org',
            'fa': 'fa.uncyc.org',
            'fi': 'hiki.pedia.ws',
            'fo': 'www.fo.ikkepedia.org',
            'fr': 'desencyclopedie.wikia.com',
            'fy': 'unsyklopedy.org',
            'ga': 'ga.uncyc.org',
            'gl': 'desgalipedia.org',
            'got': 'unsaiklopedia.org',
            'grc': 'kakapedia.org',
            'he': 'eincyclopedia.wikia.com',
            'hr': 'hr.neciklopedija.org',
            'hu': 'unciklopedia.org',
            'hy': 'angragitaran.org',
            'id': 'tolololpedia.wikia.com',
            'ie': 'ninciclopedia.org',
            'info': 'uncyclopedia.info',
            'io': 'io.neciklopedio.org',
            'is': 'is.ikkepedia.org',
            'it': 'nonciclopedia.wikia.com',
            'ja': 'ansaikuropedia.org',
            'jv': 'ndhablek.wikia.com',
            'ka': 'anciklopedia.org',
            'km': 'km.uncyclopedia.info',
            'ko': 'uncyclopedia.kr',
            'la': 'uncapaedia.org',
            'lb': 'kengencyclopedia.org',
            'li': 'kwatsjpedia.org',
            'lo': 'lo.uncyclopedia.info',
            'lt': 'juokopedija.org',
            'lv': 'lv.neciklopedija.org',
            'meta': 'uncyclomedia.org',
            'mg': 'hatsiklopedia.org',
            'mk': 'mk.neciklopedija.org',
            'mo': 'uichipedia.net',
            'ms': 'bodohpedia.org',
            'mwl': 'cciclopedia.org',
            'nl': 'oncyclopedia.net',
            'nn': 'ikkjepedia.org',
            'no': 'ikkepedia.org',
            'oc': 'oisquipedia.org',
            'pl': 'nonsensopedia.wikia.com',
            'pt': 'desciclopedia.org',
            'ro': 'neciclopedie.org',
            'ru': 'absurdopedia.net',
            'sco': 'scotypedia.org',
            'simple': 'simple.uncyc.org',
            'sk': 'necyklopedia.wikia.com',
            'sl': 'butalopedija.org',
            'sr': 'sr.neciklopedija.org',
            'su': 'su.goblogpedia.wikia.com',
            'sv': 'psyklopedin.org',
            'th': 'th.uncyclopedia.info',
            'tl': 'pekepedia.net',
            'tlh': 'tlh.uncyc.org',
            'tr': 'yansiklopedi.org',
            'uk': 'inciklopedia.org',
            'vls': 'kweenipedia.org',
            'yi': 'keinziklopedie.wikia.com',
            'zh': 'cn.uncyclopedia.wikia.com',
            'zh-hk': 'uncyclopedia.hk',
            'zh-tw': 'uncyclopedia.tw',
            'zombie': 'zombie.pedia.ws',
        }

        #
        # project namespaces & custom namespace lists
        #

        self.namespaces[-2] = {
            '_default': u'Media',
            'ar': u'ميديا',
            'bar': u'Medium',
            'be': u'Мультымедыя',
            'bg': u'Медия',
            'bn': u'মিডিয়া',
            'bs': u'Mediji',
            'cs': u'Média',
            'el': u'Μέσο',
            'et': u'Meedia',
            'fa': u'مدیا',
            'fo': u'Miðil',
            'fr': u'Média',
            'ga': u'Meán',
            'he': u'מדיה',
            'hr': u'Mediji',
            'hu': u'Média',
            'hy': u'Մեդիա',
            'is': u'Miðill',
            'ja': u'メディア',
            'ka': u'მედია',
            'km': u'មេឌា',
            'ko': u'미디어',
            'lo': u'ສື່',
            'lt': u'Medija',
            'mg': u'Rakitra',
            'mk': u'Медија',
            'nn': u'Filpeikar',
            'no': u'Medium',
            'oc': u'Mèdia',
            'pt': u'Mídia',
            'ru': u'Медиа',
            'sk': u'Médiá',
            'sl': u'Datoteka',
            'sr': u'Медија',
            'su': u'Média',
            'th': u'สื่อ',
            'tl': u'Midya',
            'tlh': u'Doch',
            'tr': u'Medya',
            'uk': u'Медіа',
            'yi': u'מעדיע',
            'zh-hk': u'媒體',
            'zh-tw': u'媒體',
        }

        self.namespaces[-1] = {
            '_default': u'Special',
            'af': u'Spesiaal',
            'ar': u'خاص',
            'ast': u'Especial',
            'bar': u'Spezial',
            'be': u'Адмысловае',
            'bg': u'Специални',
            'bn': u'বিশেষ',
            'bs': u'Posebno',
            'ca': u'Especial',
            'cs': u'Speciální',
            'cy': u'Arbennig',
            'da': u'Speciel',
            'de': u'Spezial',
            'el': u'Ειδικό',
            'eo': u'Speciala',
            'es': u'Especial',
            'et': u'Eri',
            'fa': u'ویژه',
            'fi': u'Toiminnot',
            'fo': u'Serstakt',
            'fr': u'Spécial',
            'fy': u'Wiki',
            'ga': u'Speisialta',
            'gl': u'Especial',
            'he': u'מיוחד',
            'hr': u'Posebno',
            'hu': u'Speciális',
            'hy': u'Սպասարկող',
            'id': u'Istimewa',
            'io': u'Specala',
            'is': u'Kerfissíða',
            'it': u'Speciale',
            'ja': u'特別',
            'jv': u'Astamiwa',
            'ka': u'სპეციალური',
            'km': u'ពិសេស',
            'ko': u'특수기능',
            'la': u'Specialis',
            'lb': u'Spezial',
            'li': u'Speciaal',
            'lo': u'ພິເສດ',
            'lt': u'Specialus',
            'mg': u'Manokana',
            'mk': u'Специјални',
            'ms': u'Khas',
            'nl': u'Speciaal',
            'nn': u'Spesial',
            'no': u'Spesial',
            'oc': u'Especial',
            'pl': u'Specjalna',
            'pt': u'Especial',
            'ru': u'Служебная',
            'sk': u'Špeciálne',
            'sl': u'Posebno',
            'sr': u'Посебно',
            'su': u'Husus',
            'th': u'พิเศษ',
            'tl': u'Natatangi',
            'tlh': u'le\'',
            'tr': u'Özel',
            'uk': u'Спеціальна',
            'vls': u'Specioal',
            'yi': u'באַזונדער',
            'zh-hk': u'特殊',
            'zh-tw': u'特殊',
        }

        self.namespaces[1] = {
            '_default': u'Talk',
            'af': u'Bespreking',
            'ar': u'نقاش',
            'ast': u'Alderique',
            'bar': u'Diskussion',
            'be': u'Размовы',
            'bg': u'Беседа',
            'bn': u'আলাপ',
            'bs': u'Razgovor',
            'ca': u'Discussió',
            'cs': u'Diskuse',
            'cy': u'Sgwrs',
            'da': u'Diskussion',
            'de': u'Diskussion',
            'el': u'Συζήτηση',
            'eo': u'Diskuto',
            'es': u'Discusión',
            'et': u'Arutelu',
            'fa': u'بحث',
            'fi': u'Keskustelu',
            'fo': u'Kjak',
            'fr': u'Discussion',
            'fy': u'Oerlis',
            'ga': u'Plé',
            'gl': u'Conversa',
            'he': u'שיחה',
            'hr': u'Razgovor',
            'hu': u'Vita',
            'hy': u'Քննարկում',
            'id': u'Pembicaraan',
            'io': u'Debato',
            'is': u'Spjall',
            'it': u'Discussione',
            'ja': u'トーク',
            'jv': u'Dhiskusi',
            'ka': u'განხილვა',
            'km': u'ការពិភាក្សា',
            'ko': u'토론',
            'la': u'Disputatio',
            'lb': u'Diskussioun',
            'li': u'Euverlèk',
            'lo': u'ສົນທະນາ',
            'lt': u'Aptarimas',
            'lv': u'Diskusija',
            'mg': u'Dinika',
            'mk': u'Разговор',
            'mo': u'Discuție',
            'ms': u'Perbincangan',
            'mwl': u'Cumbersa',
            'nl': u'Overleg',
            'nn': u'Diskusjon',
            'no': u'Diskusjon',
            'oc': u'Discutir',
            'pl': u'Dyskusja',
            'pt': u'Discussão',
            'ro': u'Discuție',
            'ru': u'Обсуждение',
            'sk': u'Diskusia',
            'sl': u'Pogovor',
            'sr': u'Разговор',
            'su': u'Obrolan',
            'sv': u'Diskussion',
            'th': u'พูดคุย',
            'tl': u'Usapan',
            'tlh': u'ja\'chuq',
            'tr': u'Tartışma',
            'uk': u'Обговорення',
            'vls': u'Discuusje',
            'yi': u'רעדן',
            'zh-hk': u'討論',
            'zh-tw': u'討論',
        }

        self.namespaces[2] = {
            '_default': u'User',
            'af': u'Gebruiker',
            'ar': u'مستخدم',
            'ast': u'Usuariu',
            'bar': u'Benutzer',
            'be': u'Удзельнік',
            'bg': u'Потребител',
            'bn': u'ব্যবহারকারী',
            'bs': u'Korisnik',
            'ca': u'Usuari',
            'cs': u'Uživatel',
            'cy': u'Defnyddiwr',
            'da': u'Bruger',
            'de': u'Benutzer',
            'el': u'Χρήστης',
            'eo': u'Vikipediisto',
            'es': u'Usuario',
            'et': u'Kasutaja',
            'fa': u'کاربر',
            'fi': u'Käyttäjä',
            'fo': u'Brúkari',
            'fr': u'Utilisateur',
            'fy': u'Meidogger',
            'ga': u'Úsáideoir',
            'gl': u'Usuario',
            'he': u'משתמש',
            'hr': u'Suradnik',
            'hu': u'Szerkesztő',
            'hy': u'Մասնակից',
            'id': u'Pengguna',
            'io': u'Uzanto',
            'is': u'Notandi',
            'it': u'Utente',
            'ja': u'利用者',
            'jv': u'Panganggo',
            'ka': u'მომხმარებელი',
            'km': u'អ្នកប្រើប្រាស់',
            'ko': u'사용자',
            'la': u'Usor',
            'lb': u'Benotzer',
            'li': u'Gebroeker',
            'lo': u'ຜູ້ໃຊ້',
            'lt': u'Naudotojas',
            'lv': u'Lietotājs',
            'mg': u'Mpikambana',
            'mk': u'Корисник',
            'mo': u'Utilizator',
            'ms': u'Pengguna',
            'mwl': u'Outelizador',
            'nl': u'Gebruiker',
            'nn': u'Brukar',
            'no': u'Bruker',
            'oc': u'Utilizaire',
            'pl': u'Użytkownik',
            'pt': u'Usuário',
            'ro': u'Utilizator',
            'ru': u'Участник',
            'sk': u'Redaktor',
            'sl': u'Uporabnik',
            'sr': u'Корисник',
            'su': u'Pamaké',
            'sv': u'Användare',
            'th': u'ผู้ใช้',
            'tl': u'Tagagamit',
            'tlh': u'lo\'wI\'',
            'tr': u'Kullanıcı',
            'uk': u'Користувач',
            'vls': u'Gebruker',
            'yi': u'באַניצער',
            'zh-hk': u'用戶',
            'zh-tw': u'用戶',
        }

        self.namespaces[3] = {
            '_default': u'User talk',
            'af': u'Gebruikerbespreking',
            'ar': u'نقاش المستخدم',
            'ast': u'Usuariu alderique',
            'bar': u'Benutzer Diskussion',
            'be': u'Размовы з удзельнікам',
            'bg': u'Потребител беседа',
            'bn': u'ব্যবহারকারী আলাপ',
            'bs': u'Razgovor sa korisnikom',
            'ca': u'Usuari Discussió',
            'cs': u'Uživatel diskuse',
            'cy': u'Sgwrs Defnyddiwr',
            'da': u'Brugerdiskussion',
            'de': u'Benutzer Diskussion',
            'el': u'Συζήτηση χρήστη',
            'eo': u'Vikipediista diskuto',
            'es': u'Usuario Discusión',
            'et': u'Kasutaja arutelu',
            'fa': u'بحث کاربر',
            'fi': u'Keskustelu käyttäjästä',
            'fo': u'Brúkarakjak',
            'fr': u'Discussion utilisateur',
            'fy': u'Meidogger oerlis',
            'ga': u'Plé úsáideora',
            'gl': u'Conversa usuario',
            'he': u'שיחת משתמש',
            'hr': u'Razgovor sa suradnikom',
            'hu': u'Szerkesztővita',
            'hy': u'Մասնակցի քննարկում',
            'id': u'Pembicaraan Pengguna',
            'io': u'Uzanto Debato',
            'is': u'Notandaspjall',
            'it': u'Discussioni utente',
            'ja': u'利用者・トーク',
            'jv': u'Dhiskusi Panganggo',
            'ka': u'მომხმარებლის განხილვა',
            'km': u'ការពិភាក្សារបស់អ្នកប្រើប្រាស់',
            'ko': u'사용자토론',
            'la': u'Disputatio Usoris',
            'lb': u'Benotzer Diskussioun',
            'li': u'Euverlèk gebroeker',
            'lo': u'ສົນທະນາຂອງຜູ້ໃຊ້',
            'lt': u'Naudotojo aptarimas',
            'lv': u'Lietotāja diskusija',
            'mg': u'Dinika amin\'ny mpikambana',
            'mk': u'Разговор со корисник',
            'mo': u'Discuție Utilizator',
            'ms': u'Perbincangan Pengguna',
            'mwl': u'Cumbersa outelizador',
            'nl': u'Overleg gebruiker',
            'nn': u'Brukardiskusjon',
            'no': u'Brukerdiskusjon',
            'oc': u'Discussion Utilizaire',
            'pl': u'Dyskusja użytkownika',
            'pt': u'Usuário Discussão',
            'ro': u'Discuție Utilizator',
            'ru': u'Обсуждение участника',
            'sk': u'Diskusia s redaktorom',
            'sl': u'Uporabniški pogovor',
            'sr': u'Разговор са корисником',
            'su': u'Obrolan pamaké',
            'sv': u'Användardiskussion',
            'th': u'คุยกับผู้ใช้',
            'tl': u'Usapang tagagamit',
            'tlh': u'lo\'wI\' ja\'chuq',
            'tr': u'Kullanıcı mesaj',
            'uk': u'Обговорення користувача',
            'vls': u'Discuusje gebruker',
            'yi': u'באַניצער רעדן',
            'zh-hk': u'用戶討論',
            'zh-tw': u'用戶討論',
        }

        self.namespaces[4] = {
            '_default': u'Project',
            'af': u'Niesiklopedia',
            'ar': u'بيضيپيديا',
            'ast': u'Nunyepedia',
            'bar': u'Stupidedia',
            'be': u'Паўдурапедыя',
            'bg': u'Oxypedia',
            'bn': u'আনসাইক্লোপিডিয়া',
            'bs': u'Neciklopedija',
            'ca': u'Valenciclopèdia',
            'common': u'UnCommons',
            'cs': u'Necyklopedie',
            'cy': u'Celwyddoniadur',
            'da': u'Spademanns Leksikon',
            'de': u'Uncyclopedia',
            'dlm': u'Neciklopedija',
            'el': u'Φρικηπαίδεια',
            'en': u'Uncyclopedia',
            'eo': u'Neciklopedio',
            'es': u'Inciclopedia',
            'et': u'Ebatsüklopeedia',
            'fa': u'نانشنامه',
            'fi': u'Hikipedia',
            'fo': u'Wikkepedia',
            'fr': u'Désencyclopédie',
            'fy': u'Unsyklopedy',
            'ga': u'Frithchiclipéid',
            'gl': u'Desgalipedia',
            'got': u'Unsaiklopedia',
            'grc': u'Κακαπαιδεια',
            'he': u'איןציקלופדיה',
            'hr': u'Neciklopedija',
            'hu': u'Unciklopédia',
            'hy': u'Angragitaran',
            'id': u'Tolololpedia',
            'ie': u'Ninciclopedia',
            'info': u'Uncyclopaedia',
            'io': u'Neciklopedio',
            'is': u'Ekkipedia',
            'it': u'Nonciclopedia',
            'ja': u'Uncyclopedia',
            'jv': u'Ndhablek',
            'ka': u'Anciklopedia',
            'km': u'Uncyclopedia',
            'ko': u'백괴사전',
            'la': u'Necyclopaedia',
            'lb': u'Kengencyclopedia',
            'li': u'Kwatsjpedia',
            'lo': u'Uncyclopedia',
            'lt': u'Juokopediją',
            'lv': u'Neciklopēdija',
            'meta': u'UnMeta',
            'mg': u'Hatsiklopedia',
            'mk': u'Нециклопедий',
            'mo': u'Neciclopedia',
            'ms': u'Bodohpedia',
            'mwl': u'Çciclopédia',
            'nl': u'Oncyclopedia',
            'nn': u'Ikkjepedia',
            'no': u'Ikkepedia',
            'oc': u'Oisquipedia',
            'pl': u'Nonsensopedia',
            'pt': u'Desciclopédia',
            'ro': u'Neciclopedie',
            'ru': u'Абсурдопедия',
            'sco': u'Scotypedia',
            'simple': u'Uncyclopedia',
            'sk': u'Necyklopédia',
            'sl': u'Butalopedija',
            'sr': u'Нециклопедија',
            'su': u'Goblogpedia Wiki',
            'sv': u'Psyklopedin',
            'th': u'ไร้สาระนุกรม',
            'tl': u'Pekepedia',
            'tlh': u'ghItlh\'a\'pedia',
            'tr': u'Yansiklopedi',
            'uk': u'Інциклопедія',
            'vls': u'Kweenipedia',
            'yi': u'קיינציקלאָפעדיע',
            'zh': u'伪基百科',
            'zh-hk': u'偽基百科',
            'zh-tw': u'偽基百科',
            'zombie': u'Zombiepedia',
        }

        self.namespaces[5] = {
            '_default': u'Project talk',
            'af': u'Niesiklopediabespreking',
            'ar': u'نقاش بيضيپيديا',
            'ast': u'Nunyepedia alderique',
            'bar': u'Stupidedia Diskussion',
            'be': u'Паўдурапедыя размовы',
            'bg': u'Oxypedia беседа',
            'bn': u'আনসাইক্লোপিডিয়া আলোচনা',
            'bs': u'Razgovor s Neciklopedija',
            'ca': u'Valenciclopèdia Discussió',
            'common': u'UnCommons talk',
            'cs': u'Necyklopedie diskuse',
            'cy': u'Sgwrs Celwyddoniadur',
            'da': u'Spademanns Leksikon-diskussion',
            'de': u'Uncyclopedia Diskussion',
            'dlm': u'Neciklopedija talk',
            'el': u'Φρικηπαίδεια συζήτηση',
            'en': u'Uncyclopedia talk',
            'eo': u'Neciklopedio diskuto',
            'es': u'Inciclopedia Discusión',
            'et': u'Ebatsüklopeedia arutelu',
            'fa': u'بحث نانشنامه',
            'fi': u'Keskustelu Hikipediasta',
            'fo': u'Wikkepedia-kjak',
            'fr': u'Discussion Désencyclopédie',
            'fy': u'Unsyklopedy oerlis',
            'ga': u'Plé Frithchiclipéid',
            'gl': u'Conversa Desgalipedia',
            'got': u'Unsaiklopedia talk',
            'grc': u'Κακαπαιδεια talk',
            'he': u'שיחת איןציקלופדיה',
            'hr': u'Razgovor Neciklopedija',
            'hu': u'Unciklopédia-vita',
            'hy': u'Angragitaran քննարկում',
            'id': u'Pembicaraan Tolololpedia',
            'ie': u'Ninciclopedia talk',
            'info': u'Uncyclopaedia talk',
            'io': u'Neciklopedio Debato',
            'is': u'Ekkipediaspjall',
            'it': u'Discussioni Nonciclopedia',
            'ja': u'Uncyclopedia・トーク',
            'jv': u'Dhiskusi Ndhablek',
            'ka': u'Anciklopedia განხილვა',
            'km': u'ការពិភាក្សាអំពីUncyclopedia',
            'ko': u'백괴사전토론',
            'la': u'Disputatio Necyclopaediae',
            'lb': u'Kengencyclopedia Diskussioun',
            'li': u'Euverlèk Kwatsjpedia',
            'lo': u'ສົນທະນາກ່ຽວກັບUncyclopedia',
            'lt': u'Juokopediją aptarimas',
            'lv': u'Neciklopēdija diskusija',
            'meta': u'UnMeta talk',
            'mg': u'Dinika amin\'ny Hatsiklopedia',
            'mk': u'Разговор за Нециклопедий',
            'mo': u'Discuție Neciclopedia',
            'ms': u'Perbincangan Bodohpedia',
            'mwl': u'Çciclopédia cumbersa',
            'nl': u'Overleg Oncyclopedia',
            'nn': u'Ikkjepedia-diskusjon',
            'no': u'Ikkepedia-diskusjon',
            'oc': u'Discussion Oisquipedia',
            'pl': u'Dyskusja Nonsensopedia',
            'pt': u'Desciclopédia Discussão',
            'ro': u'Discuție Neciclopedie',
            'ru': u'Обсуждение Абсурдопедии',
            'sco': u'Scotypedia talk',
            'simple': u'Uncyclopedia talk',
            'sk': u'Diskusia k Necyklopédia',
            'sl': u'Pogovor o Butalopedija',
            'sr': u'Разговор о Нециклопедија',
            'su': u'Obrolan Goblogpedia Wiki',
            'sv': u'Psyklopedindiskussion',
            'th': u'คุยเรื่องไร้สาระนุกรม',
            'tl': u'Usapang Pekepedia',
            'tlh': u'ghItlh\'a\'pedia ja\'chuq',
            'tr': u'Yansiklopedi tartışma',
            'uk': u'Обговорення Інциклопедії',
            'vls': u'Discuusje Kweenipedia',
            'yi': u'קיינציקלאָפעדיע רעדן',
            'zh': u'伪基百科 talk',
            'zh-hk': u'偽基百科討論',
            'zh-tw': u'偽基百科討論',
            'zombie': u'Zombiepedia talk',
        }

        self.namespaces[6] = {
            '_default': u'File',
            'af': u'Lêer',
            'ar': u'ملف',
            'ast': u'Archivu',
            'bar': u'Datei',
            'be': u'Выява',
            'bg': u'Файл',
            'bn': u'চিত্র',
            'bs': u'Datoteka',
            'ca': u'Fitxer',
            'common': u'Image',
            'cs': u'Soubor',
            'cy': u'Delwedd',
            'da': u'Fil',
            'de': u'Datei',
            'el': u'Αρχείο',
            'eo': u'Dosiero',
            'es': u'Archivo',
            'et': u'Pilt',
            'fa': u'پرونده',
            'fi': u'Tiedosto',
            'fo': u'Mynd',
            'fr': u'Fichier',
            'fy': u'Ofbyld',
            'ga': u'Íomhá',
            'gl': u'Ficheiro',
            'he': u'קובץ',
            'hr': u'Datoteka',
            'hu': u'Fájl',
            'hy': u'Պատկեր',
            'id': u'Berkas',
            'io': u'Arkivo',
            'is': u'Mynd',
            'ja': u'ファイル',
            'jv': u'Gambar',
            'ka': u'ფაილი',
            'km': u'ឯកសារ',
            'ko': u'파일',
            'la': u'Fasciculus',
            'lb': u'Fichier',
            'li': u'Plaetje',
            'lo': u'ຮູບ',
            'lt': u'Vaizdas',
            'lv': u'Attēls',
            'mg': u'Sary',
            'mk': u'Податотека',
            'mo': u'Fișier',
            'ms': u'Fail',
            'mwl': u'Fexeiro',
            'nl': u'Bestand',
            'nn': u'Fil',
            'no': u'Fil',
            'oc': u'Fichièr',
            'pl': u'Plik',
            'pt': u'Imagem',
            'ro': u'Fișier',
            'ru': u'Файл',
            'sk': u'Súbor',
            'sl': u'Slika',
            'sr': u'Слика',
            'su': u'Gambar',
            'sv': u'Fil',
            'th': u'ไฟล์',
            'tl': u'Talaksan',
            'tlh': u'nagh beQ',
            'tr': u'Dosya',
            'uk': u'Файл',
            'vls': u'Ofbeeldienge',
            'yi': u'טעקע',
            'zh-hk': u'圖像',
            'zh-tw': u'圖像',
        }

        self.namespaces[7] = {
            '_default': u'File talk',
            'af': u'Lêerbespreking',
            'ar': u'نقاش الملف',
            'ast': u'Archivu alderique',
            'bar': u'Datei Diskussion',
            'be': u'Размовы пра выяву',
            'bg': u'Файл беседа',
            'bn': u'চিত্র আলোচনা',
            'bs': u'Razgovor o datoteci',
            'ca': u'Fitxer Discussió',
            'common': u'Image talk',
            'cs': u'Soubor diskuse',
            'cy': u'Sgwrs Delwedd',
            'da': u'Fildiskussion',
            'de': u'Datei Diskussion',
            'el': u'Συζήτηση αρχείου',
            'eo': u'Dosiera diskuto',
            'es': u'Archivo Discusión',
            'et': u'Pildi arutelu',
            'fa': u'بحث پرونده',
            'fi': u'Keskustelu tiedostosta',
            'fo': u'Myndakjak',
            'fr': u'Discussion fichier',
            'fy': u'Ofbyld oerlis',
            'ga': u'Plé íomhá',
            'gl': u'Conversa ficheiro',
            'he': u'שיחת קובץ',
            'hr': u'Razgovor o datoteci',
            'hu': u'Fájlvita',
            'hy': u'Պատկերի քննարկում',
            'id': u'Pembicaraan Berkas',
            'io': u'Arkivo Debato',
            'is': u'Myndaspjall',
            'it': u'Discussioni file',
            'ja': u'ファイル・トーク',
            'jv': u'Dhiskusi Gambar',
            'ka': u'ფაილის განხილვა',
            'km': u'ការពិភាក្សាអំពីឯកសារ',
            'ko': u'파일토론',
            'la': u'Disputatio Fasciculi',
            'lb': u'Fichier Diskussioun',
            'li': u'Euverlèk plaetje',
            'lo': u'ສົນທະນາກ່ຽວກັບຮູບ',
            'lt': u'Vaizdo aptarimas',
            'lv': u'Attēla diskusija',
            'mg': u'Dinika amin\'ny sary',
            'mk': u'Разговор за податотека',
            'mo': u'Discuție Fișier',
            'ms': u'Perbincangan Fail',
            'mwl': u'Cumbersa fexeiro',
            'nl': u'Overleg bestand',
            'nn': u'Fildiskusjon',
            'no': u'Fildiskusjon',
            'oc': u'Discussion Fichièr',
            'pl': u'Dyskusja pliku',
            'pt': u'Imagem Discussão',
            'ro': u'Discuție Fișier',
            'ru': u'Обсуждение файла',
            'sk': u'Diskusia k súboru',
            'sl': u'Pogovor o sliki',
            'sr': u'Разговор о слици',
            'su': u'Obrolan gambar',
            'sv': u'Fildiskussion',
            'th': u'คุยเรื่องไฟล์',
            'tl': u'Usapang talaksan',
            'tlh': u'nagh beQ ja\'chuq',
            'tr': u'Dosya tartışma',
            'uk': u'Обговорення файлу',
            'vls': u'Discuusje ofbeeldienge',
            'yi': u'טעקע רעדן',
            'zh-hk': u'圖像討論',
            'zh-tw': u'圖像討論',
        }

        self.namespaces[8] = {
            '_default': u'MediaWiki',
            'ar': u'ميدياويكي',
            'bg': u'МедияУики',
            'bn': u'মিডিয়াউইকি',
            'cy': u'MediaWici',
            'fa': u'مدیاویکی',
            'fi': u'Järjestelmäviesti',
            'he': u'מדיה ויקי',
            'is': u'Melding',
            'ka': u'მედიავიკი',
            'km': u'មេឌាវិគី',
            'ko': u'미디어위키',
            'lo': u'ມີເດຍວິກິ',
            'mk': u'МедијаВики',
            'mwl': u'Biqui',
            'sr': u'МедијаВики',
            'su': u'MédiaWiki',
            'th': u'มีเดียวิกิ',
            'yi': u'מעדיעװיקי',
            'zh-hk': u'媒體偽基',
            'zh-tw': u'媒體偽基',
        }

        self.namespaces[9] = {
            '_default': u'MediaWiki talk',
            'af': u'MediaWikibespreking',
            'ar': u'نقاش ميدياويكي',
            'ast': u'MediaWiki alderique',
            'bar': u'MediaWiki Diskussion',
            'be': u'Размовы пра MediaWiki',
            'bg': u'МедияУики беседа',
            'bn': u'মিডিয়াউইকি আলোচনা',
            'bs': u'MediaWiki razgovor',
            'ca': u'MediaWiki Discussió',
            'cs': u'MediaWiki diskuse',
            'cy': u'Sgwrs MediaWici',
            'da': u'MediaWiki-diskussion',
            'de': u'MediaWiki Diskussion',
            'el': u'Συζήτηση MediaWiki',
            'eo': u'MediaWiki diskuto',
            'es': u'MediaWiki Discusión',
            'et': u'MediaWiki arutelu',
            'fa': u'بحث مدیاویکی',
            'fi': u'Keskustelu järjestelmäviestistä',
            'fo': u'MediaWiki-kjak',
            'fr': u'Discussion MediaWiki',
            'fy': u'MediaWiki oerlis',
            'ga': u'Plé MediaWiki',
            'gl': u'Conversa MediaWiki',
            'he': u'שיחת מדיה ויקי',
            'hr': u'MediaWiki razgovor',
            'hu': u'MediaWiki-vita',
            'hy': u'MediaWiki քննարկում',
            'id': u'Pembicaraan MediaWiki',
            'io': u'MediaWiki Debato',
            'is': u'Meldingarspjall',
            'it': u'Discussioni MediaWiki',
            'ja': u'MediaWiki・トーク',
            'jv': u'Dhiskusi MediaWiki',
            'ka': u'მედიავიკის განხილვა',
            'km': u'ការពិភាក្សាអំពីមេឌាវិគី',
            'ko': u'미디어위키토론',
            'la': u'Disputatio MediaWiki',
            'lb': u'MediaWiki Diskussioun',
            'li': u'Euverlèk MediaWiki',
            'lo': u'ສົນທະນາກ່ຽວກັບມີເດຍວິກິ',
            'lt': u'MediaWiki aptarimas',
            'lv': u'MediaWiki diskusija',
            'mg': u'Dinika amin\'ny MediaWiki',
            'mk': u'Разговор за МедијаВики',
            'mo': u'Discuție MediaWiki',
            'ms': u'Perbincangan MediaWiki',
            'mwl': u'Cumbersa Biqui',
            'nl': u'Overleg MediaWiki',
            'nn': u'MediaWiki-diskusjon',
            'no': u'MediaWiki-diskusjon',
            'oc': u'Discussion MediaWiki',
            'pl': u'Dyskusja MediaWiki',
            'pt': u'MediaWiki Discussão',
            'ro': u'Discuție MediaWiki',
            'ru': u'Обсуждение MediaWiki',
            'sk': u'Diskusia k MediaWiki',
            'sl': u'Pogovor o MediaWiki',
            'sr': u'Разговор о МедијаВикију',
            'su': u'Obrolan MédiaWiki',
            'sv': u'MediaWiki-diskussion',
            'th': u'คุยเรื่องมีเดียวิกิ',
            'tl': u'Usapang MediaWiki',
            'tlh': u'MediaWiki ja\'chuq',
            'tr': u'MediaWiki tartışma',
            'uk': u'Обговорення MediaWiki',
            'vls': u'Discuusje MediaWiki',
            'yi': u'מעדיעװיקי רעדן',
            'zh-hk': u'媒體偽基討論',
            'zh-tw': u'媒體偽基討論',
        }

        self.namespaces[10] = {
            '_default': u'Template',
            'af': u'Sjabloon',
            'ar': u'قالب',
            'ast': u'Plantía',
            'bar': u'Vorlage',
            'be': u'Шаблон',
            'bg': u'Шаблон',
            'bn': u'টেমপ্লেট',
            'bs': u'Šablon',
            'ca': u'Plantilla',
            'cs': u'Šablona',
            'cy': u'Nodyn',
            'da': u'Skabelon',
            'de': u'Vorlage',
            'el': u'Πρότυπο',
            'eo': u'Ŝablono',
            'es': u'Plantilla',
            'et': u'Mall',
            'fa': u'الگو',
            'fi': u'Malline',
            'fo': u'Fyrimynd',
            'fr': u'Modèle',
            'fy': u'Berjocht',
            'ga': u'Teimpléad',
            'gl': u'Modelo',
            'he': u'תבנית',
            'hr': u'Predložak',
            'hu': u'Sablon',
            'hy': u'Կաղապար',
            'id': u'Templat',
            'io': u'Shablono',
            'is': u'Snið',
            'ja': u'テンプレート',
            'jv': u'Cithakan',
            'ka': u'თარგი',
            'km': u'ទំព័រគំរូ',
            'ko': u'틀',
            'la': u'Formula',
            'lb': u'Schabloun',
            'li': u'Sjabloon',
            'lo': u'ແມ່ແບບ',
            'lt': u'Šablonas',
            'lv': u'Veidne',
            'mg': u'Endrika',
            'mk': u'Шаблон',
            'mo': u'Format',
            'ms': u'Templat',
            'mwl': u'Modelo',
            'nl': u'Sjabloon',
            'nn': u'Mal',
            'no': u'Mal',
            'oc': u'Modèl',
            'pl': u'Szablon',
            'pt': u'Predefinição',
            'ro': u'Format',
            'ru': u'Шаблон',
            'sk': u'Šablóna',
            'sl': u'Predloga',
            'sr': u'Шаблон',
            'su': u'Citakan',
            'sv': u'Mall',
            'th': u'แม่แบบ',
            'tl': u'Suleras',
            'tlh': u'chen\'ay\'',
            'tr': u'Şablon',
            'uk': u'Шаблон',
            'vls': u'Patrôon',
            'yi': u'מוסטער',
            'zh-hk': u'範本',
            'zh-tw': u'範本',
        }

        self.namespaces[11] = {
            '_default': u'Template talk',
            'af': u'Sjabloonbespreking',
            'ar': u'نقاش القالب',
            'ast': u'Plantía alderique',
            'bar': u'Vorlage Diskussion',
            'be': u'Размовы пра шаблон',
            'bg': u'Шаблон беседа',
            'bn': u'টেমপ্লেট আলোচনা',
            'bs': u'Razgovor o šablonu',
            'ca': u'Plantilla Discussió',
            'cs': u'Šablona diskuse',
            'cy': u'Sgwrs Nodyn',
            'da': u'Skabelondiskussion',
            'de': u'Vorlage Diskussion',
            'el': u'Συζήτηση προτύπου',
            'eo': u'Ŝablona diskuto',
            'es': u'Plantilla Discusión',
            'et': u'Malli arutelu',
            'fa': u'بحث الگو',
            'fi': u'Keskustelu mallineesta',
            'fo': u'Fyrimyndakjak',
            'fr': u'Discussion modèle',
            'fy': u'Berjocht oerlis',
            'ga': u'Plé teimpléid',
            'gl': u'Conversa modelo',
            'he': u'שיחת תבנית',
            'hr': u'Razgovor o predlošku',
            'hu': u'Sablonvita',
            'hy': u'Կաղապարի քննարկում',
            'id': u'Pembicaraan Templat',
            'io': u'Shablono Debato',
            'is': u'Sniðaspjall',
            'it': u'Discussioni template',
            'ja': u'テンプレート・トーク',
            'jv': u'Dhiskusi Cithakan',
            'ka': u'თარგის განხილვა',
            'km': u'ការពិភាក្សាអំពីទំព័រគំរូ',
            'ko': u'틀토론',
            'la': u'Disputatio Formulae',
            'lb': u'Schabloun Diskussioun',
            'li': u'Euverlèk sjabloon',
            'lo': u'ສົນທະນາກ່ຽວກັບແມ່ແບບ',
            'lt': u'Šablono aptarimas',
            'lv': u'Veidnes diskusija',
            'mg': u'Dinika amin\'ny endrika',
            'mk': u'Разговор за шаблон',
            'mo': u'Discuție Format',
            'ms': u'Perbincangan Templat',
            'mwl': u'Cumbersa Modelo',
            'nl': u'Overleg sjabloon',
            'nn': u'Maldiskusjon',
            'no': u'Maldiskusjon',
            'oc': u'Discussion Modèl',
            'pl': u'Dyskusja szablonu',
            'pt': u'Predefinição Discussão',
            'ro': u'Discuție Format',
            'ru': u'Обсуждение шаблона',
            'sk': u'Diskusia k šablóne',
            'sl': u'Pogovor o predlogi',
            'sr': u'Разговор о шаблону',
            'su': u'Obrolan citakan',
            'sv': u'Malldiskussion',
            'th': u'คุยเรื่องแม่แบบ',
            'tl': u'Usapang suleras',
            'tlh': u'chen\'ay\' ja\'chuq',
            'tr': u'Şablon tartışma',
            'uk': u'Обговорення шаблону',
            'vls': u'Discuusje patrôon',
            'yi': u'מוסטער רעדן',
            'zh-hk': u'範本討論',
            'zh-tw': u'範本討論',
        }

        self.namespaces[12] = {
            '_default': u'Help',
            'af': u'Hulp',
            'ar': u'مساعدة',
            'ast': u'Aida',
            'bar': u'Hilfe',
            'be': u'Даведка',
            'bg': u'Помощ',
            'bn': u'সাহায্য',
            'bs': u'Pomoć',
            'ca': u'Ajuda',
            'cs': u'Nápověda',
            'cy': u'Cymorth',
            'da': u'Hjælp',
            'de': u'Hilfe',
            'el': u'Βοήθεια',
            'eo': u'Helpo',
            'es': u'Ayuda',
            'et': u'Juhend',
            'fa': u'راهنما',
            'fi': u'Ohje',
            'fo': u'Hjálp',
            'fr': u'Aide',
            'fy': u'Hulp',
            'ga': u'Cabhair',
            'gl': u'Axuda',
            'he': u'מדריך',
            'hr': u'Pomoć',
            'hu': u'Segítség',
            'hy': u'Օգնություն',
            'id': u'Bantuan',
            'io': u'Helpo',
            'is': u'Hjálp',
            'it': u'Aiuto',
            'ja': u'ヘルプ',
            'jv': u'Pitulung',
            'ka': u'დახმარება',
            'km': u'ជំនួយ',
            'ko': u'도움말',
            'la': u'Auxilium',
            'lb': u'Hëllef',
            'lo': u'ຊ່ວຍເຫຼືອ',
            'lt': u'Pagalba',
            'lv': u'Palīdzība',
            'mg': u'Fanoroana',
            'mk': u'Помош',
            'mo': u'Ajutor',
            'ms': u'Bantuan',
            'mwl': u'Ajuda',
            'nn': u'Hjelp',
            'no': u'Hjelp',
            'oc': u'Ajuda',
            'pl': u'Pomoc',
            'pt': u'Ajuda',
            'ro': u'Ajutor',
            'ru': u'Справка',
            'sk': u'Pomoc',
            'sl': u'Pomoč',
            'sr': u'Помоћ',
            'su': u'Pitulung',
            'sv': u'Hjälp',
            'th': u'วิธีใช้',
            'tl': u'Tulong',
            'tlh': u'QaH',
            'tr': u'Yardım',
            'uk': u'Довідка',
            'vls': u'Ulpe',
            'yi': u'הילף',
            'zh-hk': u'協助',
            'zh-tw': u'協助',
        }

        self.namespaces[13] = {
            '_default': u'Help talk',
            'af': u'Hulpbespreking',
            'ar': u'نقاش المساعدة',
            'ast': u'Aida alderique',
            'bar': u'Hilfe Diskussion',
            'be': u'Размовы пра даведку',
            'bg': u'Помощ беседа',
            'bn': u'সাহায্য আলোচনা',
            'bs': u'Razgovor o pomoći',
            'ca': u'Ajuda Discussió',
            'cs': u'Nápověda diskuse',
            'cy': u'Sgwrs Cymorth',
            'da': u'Hjælp-diskussion',
            'de': u'Hilfe Diskussion',
            'el': u'Συζήτηση βοήθειας',
            'eo': u'Helpa diskuto',
            'es': u'Ayuda Discusión',
            'et': u'Juhendi arutelu',
            'fa': u'بحث راهنما',
            'fi': u'Keskustelu ohjeesta',
            'fo': u'Hjálparkjak',
            'fr': u'Discussion aide',
            'fy': u'Hulp oerlis',
            'ga': u'Plé cabhrach',
            'gl': u'Conversa axuda',
            'he': u'שיחת מדריך',
            'hr': u'Razgovor o pomoći',
            'hu': u'Segítségvita',
            'hy': u'Օգնության քննարկում',
            'id': u'Pembicaraan Bantuan',
            'io': u'Helpo Debato',
            'is': u'Hjálparspjall',
            'it': u'Discussioni aiuto',
            'ja': u'ヘルプ・トーク',
            'jv': u'Dhiskusi Pitulung',
            'ka': u'დახმარების განხილვა',
            'km': u'ការពិភាក្សាអំពីជំនួយ',
            'ko': u'도움말토론',
            'la': u'Disputatio Auxilii',
            'lb': u'Hëllef Diskussioun',
            'li': u'Euverlèk help',
            'lo': u'ສົນທະນາກ່ຽວກັບຊ່ວຍເຫຼືອ',
            'lt': u'Pagalbos aptarimas',
            'lv': u'Palīdzības diskusija',
            'mg': u'Dinika amin\'ny fanoroana',
            'mk': u'Разговор за помош',
            'mo': u'Discuție Ajutor',
            'ms': u'Perbincangan Bantuan',
            'mwl': u'Cumbersa ajuda',
            'nl': u'Overleg help',
            'nn': u'Hjelpdiskusjon',
            'no': u'Hjelpdiskusjon',
            'oc': u'Discussion Ajuda',
            'pl': u'Dyskusja pomocy',
            'pt': u'Ajuda Discussão',
            'ro': u'Discuție Ajutor',
            'ru': u'Обсуждение справки',
            'sk': u'Diskusia k pomoci',
            'sl': u'Pogovor o pomoči',
            'sr': u'Разговор о помоћи',
            'su': u'Obrolan pitulung',
            'sv': u'Hjälpdiskussion',
            'th': u'คุยเรื่องวิธีใช้',
            'tl': u'Usapang tulong',
            'tlh': u'QaH ja\'chuq',
            'tr': u'Yardım tartışma',
            'uk': u'Обговорення довідки',
            'vls': u'Discuusje ulpe',
            'yi': u'הילף רעדן',
            'zh-hk': u'協助討論',
            'zh-tw': u'協助討論',
        }

        self.namespaces[14] = {
            '_default': u'Category',
            'af': u'Kategorie',
            'ar': u'تصنيف',
            'ast': u'Categoría',
            'bar': u'Kategorie',
            'be': u'Катэгорыя',
            'bg': u'Категория',
            'bn': u'বিষয়শ্রেণী',
            'bs': u'Kategorija',
            'ca': u'Categoria',
            'cs': u'Kategorie',
            'cy': u'Categori',
            'da': u'Kategori',
            'de': u'Kategorie',
            'el': u'Κατηγορία',
            'eo': u'Kategorio',
            'es': u'Categoría',
            'et': u'Kategooria',
            'fa': u'رده',
            'fi': u'Luokka',
            'fo': u'Bólkur',
            'fr': u'Catégorie',
            'fy': u'Kategory',
            'ga': u'Catagóir',
            'gl': u'Categoría',
            'he': u'קטגוריה',
            'hr': u'Kategorija',
            'hu': u'Kategória',
            'hy': u'Կատեգորիա',
            'id': u'Kategori',
            'io': u'Kategorio',
            'is': u'Flokkur',
            'it': u'Categoria',
            'ja': u'カテゴリ',
            'jv': u'Kategori',
            'ka': u'კატეგორია',
            'km': u'ចំនាត់ថ្នាក់ក្រុម',
            'ko': u'분류',
            'la': u'Categoria',
            'lb': u'Kategorie',
            'li': u'Categorie',
            'lo': u'ໝວດ',
            'lt': u'Kategorija',
            'lv': u'Kategorija',
            'mg': u'Sokajy',
            'mk': u'Категорија',
            'mo': u'Categorie',
            'ms': u'Kategori',
            'mwl': u'Catadorie',
            'nl': u'Categorie',
            'nn': u'Kategori',
            'no': u'Kategori',
            'oc': u'Categoria',
            'pl': u'Kategoria',
            'pt': u'Categoria',
            'ro': u'Categorie',
            'ru': u'Категория',
            'sk': u'Kategória',
            'sl': u'Kategorija',
            'sr': u'Категорија',
            'su': u'Kategori',
            'sv': u'Kategori',
            'th': u'หมวดหมู่',
            'tl': u'Kaurian',
            'tlh': u'Segh',
            'tr': u'Kategori',
            'uk': u'Категорія',
            'vls': u'Categorie',
            'yi': u'קאַטעגאָריע',
            'zh-hk': u'分類',
            'zh-tw': u'分類',
        }

        self.namespaces[15] = {
            '_default': u'Category talk',
            'af': u'Kategoriebespreking',
            'ar': u'نقاش التصنيف',
            'ast': u'Categoría alderique',
            'bar': u'Kategorie Diskussion',
            'be': u'Размовы пра катэгорыю',
            'bg': u'Категория беседа',
            'bn': u'বিষয়শ্রেণী আলোচনা',
            'bs': u'Razgovor o kategoriji',
            'ca': u'Categoria Discussió',
            'cs': u'Kategorie diskuse',
            'cy': u'Sgwrs Categori',
            'da': u'Kategoridiskussion',
            'de': u'Kategorie Diskussion',
            'el': u'Συζήτηση κατηγορίας',
            'eo': u'Kategoria diskuto',
            'es': u'Categoría Discusión',
            'et': u'Kategooria arutelu',
            'fa': u'بحث رده',
            'fi': u'Keskustelu luokasta',
            'fo': u'Bólkakjak',
            'fr': u'Discussion catégorie',
            'fy': u'Kategory oerlis',
            'ga': u'Plé catagóire',
            'gl': u'Conversa categoría',
            'he': u'שיחת קטגוריה',
            'hr': u'Razgovor o kategoriji',
            'hu': u'Kategóriavita',
            'hy': u'Կատեգորիայի քննարկում',
            'id': u'Pembicaraan Kategori',
            'io': u'Kategorio Debato',
            'is': u'Flokkaspjall',
            'it': u'Discussioni categoria',
            'ja': u'カテゴリ・トーク',
            'jv': u'Dhiskusi Kategori',
            'ka': u'კატეგორიის განხილვა',
            'km': u'ការពិភាក្សាអំពីចំនាត់ថ្នាក់ក្រុម',
            'ko': u'분류토론',
            'la': u'Disputatio Categoriae',
            'lb': u'Kategorie Diskussioun',
            'li': u'Euverlèk categorie',
            'lo': u'ສົນທະນາກ່ຽວກັບໝວດ',
            'lt': u'Kategorijos aptarimas',
            'lv': u'Kategorijas diskusija',
            'mg': u'Dinika amin\'ny sokajy',
            'mk': u'Разговор за категорија',
            'mo': u'Discuție Categorie',
            'ms': u'Perbincangan Kategori',
            'mwl': u'Cumbersa catadorie',
            'nl': u'Overleg categorie',
            'nn': u'Kategoridiskusjon',
            'no': u'Kategoridiskusjon',
            'oc': u'Discussion Categoria',
            'pl': u'Dyskusja kategorii',
            'pt': u'Categoria Discussão',
            'ro': u'Discuție Categorie',
            'ru': u'Обсуждение категории',
            'sk': u'Diskusia ku kategórii',
            'sl': u'Pogovor o kategoriji',
            'sr': u'Разговор о категорији',
            'su': u'Obrolan kategori',
            'sv': u'Kategoridiskussion',
            'th': u'คุยเรื่องหมวดหมู่',
            'tl': u'Usapang kaurian',
            'tlh': u'Segh ja\'chuq',
            'tr': u'Kategori tartışma',
            'uk': u'Обговорення категорії',
            'vls': u'Discuusje categorie',
            'yi': u'קאַטעגאָריע רעדן',
            'zh-hk': u'分類討論',
            'zh-tw': u'分類討論',
        }

        self.namespaces[16] = {
            'dlm': u'Necikloparaula',
            'et': u'Foorum',
            'fi': u'Foorumi',
            'got': u'Forum',
            'info': u'Game',
            'meta': u'UnSource',
            'mo': u'Necţionar',
            'nl': u'Portaal',
            'simple': u'HowTo',
            'th': u'อันไซโคลพีเดีย',
            'zh-hk': u'偽基新聞',
            'zh-tw': u'偽基新聞',
        }

        self.namespaces[17] = {
            'dlm': u'Necikloparaula talk',
            'fi': u'Keskustelu foorumista',
            'got': u'Forum gawaurdja',
            'info': u'Game talk',
            'meta': u'UnSource talk',
            'mo': u'Discuție Necţionar',
            'nl': u'Overleg portaal',
            'simple': u'HowTo talk',
            'th': u'คุยเรื่องอันไซโคลพีเดีย',
            'zh-hk': u'偽基新聞討論',
            'zh-tw': u'偽基新聞討論',
        }

        self.namespaces[18] = {
            'fi': u'Hikinews',
            'got': u'𐌰𐍂𐌼𐌰𐌹𐍉',
            'meta': u'UnSpecies',
            'nl': u'OnNieuws',
            'pt': u'Fatos',
            'simple': u'Undex',
            'th': u'ไร้ข่าว',
            'zh-hk': u'偽基辭典',
            'zh-tw': u'偽基辭典',
        }

        self.namespaces[19] = {
            'fi': u'Keskustelu Hikinewseistä',
            'got': u'𐌰𐍂𐌼𐌰𐌹𐍉 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰',
            'meta': u'UnSpecies talk',
            'nl': u'Overleg OnNieuws',
            'pt': u'Fatos Discussão',
            'simple': u'Undex talk',
            'th': u'คุยเรื่องไร้ข่าว',
            'zh-hk': u'偽基辭典討論',
            'zh-tw': u'偽基辭典討論',
        }

        self.namespaces[20] = {
            'fi': u'Hiktionary',
            'got': u'𐍆𐌰𐌹𐌰𐌽𐍅𐌰𐍂𐌳𐌰𐌱𐍉𐌺𐌰',
            'nl': u'Onwoordenboek',
            'pt': u'Forum',
            'simple': u'Userbox',
            'th': u'ไร้วิทยาลัย',
            'zh-hk': u'動漫遊戲',
            'zh-tw': u'動漫遊戲',
        }

        self.namespaces[21] = {
            'fi': u'Keskustelu Hiktionarysta',
            'got': u'𐍆𐌰𐌹𐌰𐌽𐍅𐌰𐍂𐌳𐌰𐌱𐍉𐌺𐌰 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰',
            'nl': u'Overleg Onwoordenboek',
            'pt': u'Forum Discussão',
            'simple': u'Userbox talk',
            'th': u'คุยเรื่องไร้วิทยาลัย',
            'zh-hk': u'動漫遊戲討論',
            'zh-tw': u'動漫遊戲討論',
        }

        self.namespaces[22] = {
            'fi': u'Hikikirjasto',
            'meta': u'UnN',
            'nl': u'OnBoeken',
            'pt': u'Descitações',
            'simple': u'Disambiguation',
            'th': u'ไร้พจนานุกรม',
            'zh-hk': u'偽基文庫',
            'zh-tw': u'偽基文庫',
        }

        self.namespaces[23] = {
            'fi': u'Keskustelu hikikirjasta',
            'meta': u'UnN talk',
            'nl': u'Overleg OnBoeken',
            'pt': u'Descitações Discussão',
            'simple': u'Disambiguation talk',
            'th': u'คุยเรื่องไร้พจนานุกรม',
            'zh-hk': u'偽基文庫討論',
            'zh-tw': u'偽基文庫討論',
        }

        self.namespaces[24] = {
            'fi': u'Hikisitaatit',
            'meta': u'Forum',
            'ro': u'Forum',
            'simple': u'Forum',
            'th': u'ไร้ชีวประวัติ',
            'zh-hk': u'主題展館',
            'zh-tw': u'主題展館',
        }

        self.namespaces[25] = {
            'fi': u'Keskustelu hikisitaatista',
            'meta': u'Forum talk',
            'ro': u'Discuție Forum',
            'simple': u'Forum talk',
            'th': u'คุยเรื่องไร้ชีวประวัติ',
            'zh-hk': u'主題展館討論',
            'zh-tw': u'主題展館討論',
        }

        self.namespaces[26] = {
            'meta': u'Babel',
            'nl': u'OnZinnen',
            'ro': u'Necimanuale',
            'simple': u'UnNews',
            'th': u'สภาน้ำชา',
            'zh-hk': u'論壇',
            'zh-tw': u'論壇',
        }

        self.namespaces[27] = {
            'meta': u'Babel talk',
            'nl': u'Overleg OnZinnen',
            'ro': u'Discuție Necimanuale',
            'simple': u'UnNews talk',
            'th': u'คุยเรื่องสภาน้ำชา',
        }

        self.namespaces[28] = {
            'fi': u'Hikipeli',
            'meta': u'UnRecipes',
            'nl': u'Ongerijmd',
            'simple': u'UnBooks',
            'th': u'บอร์ด',
            'zh-hk': u'詞意分道',
            'zh-tw': u'詞意分道',
        }

        self.namespaces[29] = {
            'fi': u'Hihitys Hikipelistä',
            'meta': u'UnRecipes talk',
            'nl': u'Overleg Ongerijmd',
            'simple': u'UnBooks talk',
            'th': u'คุยเรื่องบอร์ด',
            'zh-hk': u'詞意分道討論',
            'zh-tw': u'詞意分道討論',
        }

        self.namespaces[30] = {
            'fi': u'Hikiopisto',
            'meta': u'UnLeaks',
            'nl': u'Oncycloversiteit',
            'pt': u'Deslivros',
            'ro': u'Necikţionar',
            'simple': u'UnDictionary',
            'th': u'ไร้ซอร์ซ',
            'zh-hk': u'臺語',
            'zh-tw': u'臺語',
        }

        self.namespaces[31] = {
            'fi': u'Keskustelu hikikurssista',
            'meta': u'UnLeaks talk',
            'nl': u'Overleg Oncycloversiteit',
            'pt': u'Deslivros Discussão',
            'ro': u'Discuție Necikţionar',
            'simple': u'UnDictionary talk',
            'th': u'คุยเรื่องไร้ซอร์ซ',
            'zh-hk': u'臺語討論',
            'zh-tw': u'臺語討論',
        }

        self.namespaces[32] = {
            'fi': u'Hikiaineisto',
            'ja': u'Portal',
            'meta': u'UnMD',
            'nl': u'Unsyklopedy',
            'pt': u'Desentrevistas',
            'ro': u'Necicitat',
            'th': u'ไร้คำคม',
            'zh-hk': u'香港語',
            'zh-tw': u'香港語',
        }

        self.namespaces[33] = {
            'fi': u'Keskustelu hikiaineistosta',
            'ja': u'Portal talk',
            'meta': u'UnMD talk',
            'nl': u'Overleg Unsyklopedy',
            'pt': u'Desentrevistas Discussão',
            'ro': u'Discuție Necicitat',
            'th': u'คุยเรื่องไร้คำคม',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[34] = {
            'meta': u'Ezentziklopedia',
            'nl': u'Niesiklopedia',
            'pt': u'Despoesias',
            'th': u'ไร้ภาพ',
            'zh-hk': u'UnTunes',
            'zh-tw': u'UnTunes',
        }

        self.namespaces[35] = {
            'meta': u'Ezentziklopedia talk',
            'nl': u'Overleg Niesiklopedia',
            'pt': u'Despoesias Discussão',
            'th': u'คุยเรื่องไร้ภาพ',
            'zh-hk': u'UnTunes討論',
            'zh-tw': u'UnTunes討論',
        }

        self.namespaces[36] = {
            'meta': u'Nociclopeya',
            'pt': u'Interno',
            'th': u'สถานีย่อย',
        }

        self.namespaces[37] = {
            'meta': u'Nociclopeya talk',
            'pt': u'Interno Discussão',
            'th': u'คุยเรื่องสถานีย่อย',
        }

        self.namespaces[38] = {
            'meta': u'Venciclopedia',
            'pt': u'Descifras',
            'th': u'ไร้นวนิยาย',
        }

        self.namespaces[39] = {
            'meta': u'Venciclopedia talk',
            'pt': u'Descifras Discussão',
            'th': u'คุยเรื่องไร้นวนิยาย',
        }

        self.namespaces[40] = {
            'meta': u'Nunciclopedia',
        }

        self.namespaces[41] = {
            'meta': u'Nunciclopedia talk',
        }

        self.namespaces[100] = {
            'bar': u'Portal',
            'de': u'UnNews',
            'fa': u'درگاه',
            'gl': u'Desgalicitas',
            'he': u'איןציטוט',
            'ko': u'구백괴게임',
            'no': u'Ikkenytt',
            'pl': u'Cytaty',
            'ru': u'Портал',
            'sv': u'PsykNyheter',
            'tr': u'YanSözlük',
            'uk': u'Форум',
        }

        self.namespaces[101] = {
            'bar': u'Portal Diskussion',
            'de': u'UnNews Diskussion',
            'fa': u'بحث درگاه',
            'gl': u'Conversa Desgalicitas',
            'he': u'שיחת איןציטוט',
            'ko': u'구백괴게임토론',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'ru': u'Обсуждение портала',
            'sv': u'PsykNyheter diskussion',
            'tr': u'YanSözlük tartışma',
            'uk': u'Обговорення форуму',
        }

        self.namespaces[102] = {
            'bar': u'Diverses',
            'de': u'Undictionary',
            'en': u'UnNews',
            'gl': u'Desgalilibros',
            'ja': u'UnNews',
            'ko': u'포럼',
            'no': u'Ikktionary',
            'pl': u'NonNews',
            'sv': u'Forum',
            'tr': u'YanHaber',
        }

        self.namespaces[103] = {
            'bar': u'Diverses Diskussion',
            'de': u'Undictionary Diskussion',
            'en': u'UnNews talk',
            'gl': u'Conversa Desgalilibros',
            'ja': u'UnNews talk',
            'ko': u'포럼토론',
            'no': u'Ikktionary-diskusjon',
            'pl': u'Dyskusja NonNews',
            'sv': u'Forumdiskussion',
            'tr': u'YanHaber tartışma',
        }

        self.namespaces[104] = {
            'bar': u'Sub',
            'de': u'UnBooks',
            'en': u'Undictionary',
            'gl': u'Desgalinews',
            'ja': u'Undictionary',
            'ko': u'백괴뉴스',
            'pl': u'Nonźródła',
            'sv': u'Psyktionary',
        }

        self.namespaces[105] = {
            'bar': u'Sub Diskussion',
            'de': u'UnBooks Diskussion',
            'en': u'Undictionary talk',
            'gl': u'Conversa Desgalinews',
            'ja': u'Undictionary talk',
            'ko': u'백괴뉴스토론',
            'pl': u'Dyskusja nonźródeł',
            'sv': u'Psyktionary diskussion',
        }

        self.namespaces[106] = {
            'bar': u'Spiegelwelten',
            'en': u'Game',
            'gl': u'Desgalizionario',
            'ja': u'Game',
            'ko': u'백괴낱말사전',
            'pl': u'Słownik',
            'pt': u'Desnotícias',
            'sv': u'PsykCitat',
            'tlh': u'GhItNews',
        }

        self.namespaces[107] = {
            'bar': u'Spiegelwelten Diskussion',
            'en': u'Game talk',
            'gl': u'Conversa Desgalizionario',
            'ja': u'Game talk',
            'ko': u'백괴낱말사전토론',
            'pl': u'Dyskusja słownika',
            'pt': u'Desnotícias Discussão',
            'sv': u'PsykCitat diskussion',
            'tlh': u'GhItNews ja\'chuq',
        }

        self.namespaces[108] = {
            'en': u'Babel',
            'ko': u'해설',
            'pl': u'Gra',
            'sv': u'Spel',
            'tlh': u'Forum',
        }

        self.namespaces[109] = {
            'en': u'Babel talk',
            'ko': u'해설토론',
            'pl': u'Dyskusja gry',
            'sv': u'Speldiskussion',
            'tlh': u'Forum ja\'chuq',
        }

        self.namespaces[110] = {
            'af': u'Forum',
            'ar': u'Forum',
            'ast': u'Forum',
            'ca': u'Forum',
            'cs': u'Forum',
            'da': u'Forum',
            'de': u'Forum',
            'el': u'Forum',
            'en': u'Forum',
            'eo': u'Forum',
            'es': u'Foro',
            'fo': u'Forum',
            'fr': u'Forum',
            'fy': u'Forum',
            'gl': u'Forum',
            'he': u'בית קפה',
            'id': u'Forum',
            'ie': u'Forum',
            'io': u'Forum',
            'is': u'Forum',
            'it': u'Forum',
            'ja': u'Forum',
            'jv': u'Forum',
            'mwl': u'Forum',
            'no': u'Forum',
            'pl': u'Forum',
            'pt': u'Descionário',
            'ru': u'Форум',
            'sk': u'Forum',
            'su': u'Forum',
            'sv': u'PsykBöcker',
            'tlh': u'Holdictionary',
            'tr': u'Astroloji',
            'vls': u'Forum',
            'yi': u'Forum',
            'zh': u'Forum',
        }

        self.namespaces[111] = {
            'af': u'Forum talk',
            'ar': u'Forum talk',
            'ast': u'Forum talk',
            'ca': u'Forum talk',
            'cs': u'Forum talk',
            'da': u'Forumdiskussion',
            'de': u'Forum talk',
            'el': u'Forum talk',
            'en': u'Forum talk',
            'eo': u'Forum talk',
            'es': u'Foro Discusión',
            'fo': u'Forum talk',
            'fr': u'Discussion Forum',
            'fy': u'Forum talk',
            'gl': u'Conversa Forum',
            'he': u'שיחת בית קפה',
            'id': u'Forum talk',
            'ie': u'Forum talk',
            'io': u'Forum talk',
            'is': u'Forum talk',
            'it': u'Forum talk',
            'ja': u'Forum talk',
            'jv': u'Forum talk',
            'mwl': u'Forum talk',
            'pl': u'Dyskusja forum',
            'pt': u'Descionário Discussão',
            'ru': u'Обсуждение форума',
            'sk': u'Forum talk',
            'su': u'Forum talk',
            'sv': u'PsykBöckerdiskussion',
            'tlh': u'Holdictionary ja\'chuq',
            'tr': u'Astroloji tartışma',
            'vls': u'Forum talk',
            'yi': u'Forum talk',
            'zh': u'Forum talk',
        }

        self.namespaces[112] = {
            'cs': u'Regál',
            'en': u'UnTunes',
            'es': u'Incinoticias',
            'fr': u'Désinformation',
            'gl': u'Çciclopédia',
            'he': u'איןספר',
            'it': u'NonNotizie',
            'ja': u'UnTunes',
            'ko': u'세계관',
            'no': u'Hvordan',
            'pl': u'Portal',
            'ru': u'Абсурдилище',
            'tlh': u'Tlhbooks',
            'tr': u'Forum',
            'zh': u'伪基新闻',
        }

        self.namespaces[113] = {
            'cs': u'Regál diskuse',
            'en': u'UnTunes talk',
            'es': u'Incinoticias Discusión',
            'fr': u'Discussion Désinformation',
            'gl': u'Conversa Çciclopédia',
            'he': u'שיחת איןספר',
            'it': u'Discussioni NonNotizie',
            'ja': u'UnTunes talk',
            'ko': u'세계관토론',
            'no': u'Hvordan-diskusjon',
            'pl': u'Dyskusja portalu',
            'ru': u'Обсуждение в Абсурдилище',
            'tlh': u'Tlhbooks ja\'chuq',
            'tr': u'Forum tartışma',
            'zh': u'伪基新闻 talk',
        }

        self.namespaces[114] = {
            'cs': u'Necykloverzita',
            'es': u'Incitables',
            'fr': u'Portail',
            'he': u'איןחדש',
            'ko': u'백괴대학',
            'no': u'Hvorfor',
            'pl': u'Poradnik',
            'ru': u'Как правильно',
            'tlh': u'Ninciclopedia',
            'zh': u'伪基文库',
        }

        self.namespaces[115] = {
            'cs': u'Necykloverzita diskuse',
            'es': u'Incitables Discusión',
            'fr': u'Discussion Portail',
            'he': u'שיחת איןחדש',
            'ko': u'백괴대학토론',
            'no': u'Hvorfor-diskusjon',
            'pl': u'Dyskusja poradnika',
            'ru': u'Обсуждение руководства',
            'tlh': u'Ninciclopedia Discussion',
            'zh': u'伪基文库 talk',
        }

        self.namespaces[116] = {
            'es': u'Incijuegos',
            'he': u'איןטקסט',
            'ja': u'UnBooks',
            'ko': u'백괴인용집',
            'no': u'Ikkeratur',
            'ru': u'Абсурдотека',
            'tlh': u'GhItSpecies',
            'zh': u'伪基音乐',
        }

        self.namespaces[117] = {
            'es': u'Incijuegos Discusión',
            'he': u'שיחת איןטקסט',
            'ja': u'UnBooks talk',
            'ko': u'백괴인용집토론',
            'no': u'Ikkeratur-Diskusjon',
            'ru': u'Обсуждение Абсурдотеки',
            'tlh': u'GhItSpecies ja\'chuq',
            'zh': u'伪基音乐 talk',
        }

        self.namespaces[118] = {
            'he': u'בית קפה',
            'it': u'Giochi',
            'ko': u'백괴책',
            'no': u'Ikkeprosjekt',
            'ru': u'Несловарь',
            'tlh': u'Holfacts',
            'zh': u'伪基词典',
        }

        self.namespaces[119] = {
            'he': u'בית קפה שיחת',
            'it': u'Discussioni Giochi',
            'ko': u'백괴책토론',
            'no': u'Ikkeprosjekt-diskusjon',
            'ru': u'Обсуждение Несловаря',
            'tlh': u'Holfacts ja\'chuq',
            'zh': u'伪基词典 talk',
        }

        self.namespaces[120] = {
            'he': u'איןמילון',
            'it': u'NonCitazioni',
            'ko': u'백괴대본',
            'pt': u'Privado',
            'ru': u'Абсурдоцитатник',
            'tlh': u'Tlhconversations',
            'tr': u'YanMagazin',
        }

        self.namespaces[121] = {
            'he': u'שיחת איןמילון',
            'it': u'Discussioni NonCitazioni',
            'ko': u'백괴대본토론',
            'pt': u'Privado Discussão',
            'ru': u'Обсуждение Абсурдоцитатника',
            'tlh': u'Tlhconversations ja\'chuq',
            'tr': u'YanMagazin tartışma',
        }

        self.namespaces[122] = {
            'he': u'איןמינים',
            'it': u'NonDizionario',
            'ko': u'방법',
            'pt': u'Regra',
        }

        self.namespaces[123] = {
            'he': u'שיחת איןמינים',
            'it': u'Discussioni NonDizionario',
            'ko': u'방법토론',
            'pt': u'Regra Discussão',
        }

        self.namespaces[124] = {
            'it': u'Test',
            'pt': u'Desinopses',
        }

        self.namespaces[125] = {
            'it': u'Discussioni test',
            'pt': u'Desinopses Discussão',
        }

        self.namespaces[126] = {
            'it': u'NonLibri',
        }

        self.namespaces[127] = {
            'it': u'Discussioni NonLibri',
        }

        self.namespaces[128] = {
            'it': u'Manuali',
        }

        self.namespaces[129] = {
            'it': u'Discussioni manuali',
        }

        self.namespaces[130] = {
            'it': u'Portale',
        }

        self.namespaces[131] = {
            'it': u'Discussioni portale',
        }

        self.namespaces[150] = {
            'pt': u'Deslistas',
        }

        self.namespaces[151] = {
            'pt': u'Deslistas Discussão',
        }

        self.namespaces[400] = {
            'ar': u'Video',
            'ast': u'Video',
            'ca': u'Video',
            'cs': u'Video',
            'da': u'Video',
            'de': u'Video',
            'el': u'Video',
            'eo': u'Video',
            'es': u'Video',
            'fr': u'Video',
            'he': u'Video',
            'id': u'Video',
            'it': u'Video',
            'jv': u'Video',
            'pl': u'Video',
            'sk': u'Video',
            'su': u'Video',
            'yi': u'Video',
            'zh': u'Video',
        }

        self.namespaces[401] = {
            'ar': u'Video talk',
            'ast': u'Video talk',
            'ca': u'Video talk',
            'cs': u'Video talk',
            'da': u'Video talk',
            'de': u'Video Diskussion',
            'el': u'Video talk',
            'eo': u'Video talk',
            'es': u'Video talk',
            'fr': u'Video talk',
            'he': u'Video talk',
            'id': u'Video talk',
            'it': u'Video talk',
            'jv': u'Video talk',
            'pl': u'Dyskusja Video',
            'sk': u'Video talk',
            'su': u'Video talk',
            'yi': u'Video talk',
            'zh': u'Video talk',
        }

        self.namespaces[420] = {
            'af': u'Layer',
            'mwl': u'Layer',
        }

        self.namespaces[421] = {
            'af': u'Layer talk',
            'mwl': u'Layer talk',
        }

        self.namespaces[500] = {
            'ar': u'User blog',
            'ast': u'User blog',
            'ca': u'User blog',
            'cs': u'User blog',
            'da': u'User blog',
            'de': u'Benutzer Blog',
            'el': u'User blog',
            'eo': u'User blog',
            'es': u'Usuario Blog',
            'fr': u'Blog utilisateur',
            'he': u'User blog',
            'id': u'User blog',
            'jv': u'User blog',
            'pl': u'User blog',
            'sk': u'User blog',
            'su': u'User blog',
            'yi': u'User blog',
            'zh': u'User blog',
        }

        self.namespaces[501] = {
            'ar': u'User blog comment',
            'ast': u'User blog comment',
            'ca': u'User blog comment',
            'cs': u'User blog comment',
            'da': u'User blog comment',
            'de': u'Benutzer Blog Kommentare',
            'el': u'User blog comment',
            'eo': u'User blog comment',
            'es': u'Usuario Blog Comentario',
            'fr': u'Commentaire blog utilisateur',
            'he': u'User blog comment',
            'id': u'User blog comment',
            'jv': u'User blog comment',
            'pl': u'User blog comment',
            'sk': u'User blog comment',
            'su': u'User blog comment',
            'yi': u'User blog comment',
            'zh': u'User blog comment',
        }

        self.namespaces[502] = {
            'ar': u'Blog',
            'ast': u'Blog',
            'ca': u'Blog',
            'cs': u'Blog',
            'da': u'Blog',
            'de': u'Blog',
            'el': u'Blog',
            'eo': u'Blog',
            'es': u'Blog',
            'fr': u'Blog',
            'he': u'Blog',
            'id': u'Blog',
            'jv': u'Blog',
            'pl': u'Blog',
            'sk': u'Blog',
            'su': u'Blog',
            'yi': u'Blog',
            'zh': u'Blog',
        }

        self.namespaces[503] = {
            'ar': u'Blog talk',
            'ast': u'Blog talk',
            'ca': u'Blog talk',
            'cs': u'Blog talk',
            'da': u'Blog talk',
            'de': u'Blog Diskussion',
            'el': u'Blog talk',
            'eo': u'Blog talk',
            'es': u'Blog Discusión',
            'fr': u'Blog talk',
            'he': u'Blog talk',
            'id': u'Blog talk',
            'jv': u'Blog talk',
            'pl': u'Blog talk',
            'sk': u'Blog talk',
            'su': u'Blog talk',
            'yi': u'Blog talk',
            'zh': u'Blog talk',
        }

        # A few selected big languages for things that we do not want to loop over
        # all languages. This is only needed by the titletranslate.py module, so
        # if you carefully avoid the options, you could get away without these
        # for another wiki family.
        self.languages_by_size  = [
            'pt', 'en', 'it', 'bar', 'es', 'fr', 'ja', 'pl', 'zh-tw', 'zh-hk',
            'fi', 'ko', 'no', 'th', 'ru', 'he', 'nl', 'zh', 'de', 'da', 'cs',
            'el', 'id', 'eo', 'sk', 'hu', 'sv', 'tr', 'gl', 'uk', 'ar', 'nn',
            'fa', 'sr', 'hr', 'ca', 'ast', 'tl', 'mg', 'la', 'ro', 'lt',
            'simple', 'bg', 'lv', 'ms', 'et', 'tlh', 'mo', 'mk', 'lb', 'lo',
            'got', 'oc', 'sl', 'li', 'ka', 'mwl', 'cy', 'zombie', 'hy', 'bn',
            'dlm', 'bs', 'km', 'yi', 'be', 'vls', 'sco', 'su', 'jv', 'af',
            'grc', 'ga', 'ie', 'io', 'fy', 'is', 'fo',
        ]

        self.alphabetic_revised = [
            'af', 'ar', 'ast', 'bar', 'be', 'bg', 'bn', 'bs', 'ca', 'common',
            'cs', 'cy', 'da', 'de', 'dlm', 'el', 'en', 'eo', 'es', 'et', 'fa',
            'fi', 'fo', 'fr', 'fy', 'ga', 'gl', 'got', 'grc', 'he', 'hr', 'hu',
            'hy', 'id', 'ie', 'info', 'io', 'is', 'it', 'ja', 'jv', 'ka', 'km',
            'ko', 'la', 'lb', 'li', 'lo', 'lt', 'lv', 'meta', 'mg', 'mk', 'mo',
            'ms', 'mwl', 'nl', 'nn', 'no', 'oc', 'pl', 'pt', 'ro', 'ru', 'sco',
            'simple', 'sk', 'sl', 'sr', 'su', 'sv', 'th', 'tl', 'tlh', 'tr',
            'uk', 'vls', 'yi', 'zh', 'zh-hk', 'zh-tw', 'zombie',
        ]

    def scriptpath(self, code):
        if code == 'ko':
            return '/w'
        return ''

    def version(self, code):
        if code == 'ru':
            return '1.16.0'
        if code in ['ar', 'ast', 'ca', 'cs', 'da', 'de', 'el', 'en', 'eo', 'es',
                    'fr', 'he', 'id', 'it', 'jv', 'pl', 'sk', 'su', 'yi', 'zh']:
            return '1.16.5'
        if code in ['bar', 'ko']:
            return '1.17.0'
        if code in ['af', 'fo', 'fy', 'ie', 'io', 'is', 'mwl', 'vls']:
            return '1.19'
        return '1.17alpha'

    def code2encoding(self,code):
        return 'utf-8'

    def shared_image_repository(self, code):
        return ('common', 'common')
